# encoding: UTF-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

countries = Country.create([
  { name: 'Afghanistan' },
  { name: 'Ägypten' },
  { name: 'Åland' },
  { name: 'Albanien' },
  { name: 'Algerien' },
  { name: 'Amerikanische Jungferninseln' },
  { name: 'Amerikanisch-Samoa' },
  { name: 'Andorra' },
  { name: 'Angola' },
  { name: 'Anguilla' },
  { name: 'Antarktika' },
  { name: 'Antigua und Barbuda' },
  { name: 'Äquatorialguinea' },
  { name: 'Argentinien' },
  { name: 'Armenien' },
  { name: 'Aruba' },
  { name: 'Aserbaidschan' },
  { name: 'Äthiopien' },
  { name: 'Australien' },
  { name: 'Bahamas' },
  { name: 'Bahrain' },
  { name: 'Bangladesch' },
  { name: 'Barbados' },
  { name: 'Bassas da India' },
  { name: 'Belarus' },
  { name: 'Belgien' },
  { name: 'Belize' },
  { name: 'Benin' },
  { name: 'Bermuda' },
  { name: 'Bhutan' },
  { name: 'Bolivien' },
  { name: 'Bosnien und Herzegowina' },
  { name: 'Botsuana' },
  { name: 'Bouvetinsel' },
  { name: 'Brasilien' },
  { name: 'Britische Jungferninseln' },
  { name: 'Britisches Territorium im Indischen Ozean' },
  { name: 'Brunei Darussalam' },
  { name: 'Bulgarien' },
  { name: 'Burkina Faso' },
  { name: 'Burundi' },
  { name: 'Chile' },
  { name: 'China' },
  { name: 'Clipperton' },
  { name: 'Cookinseln' },
  { name: 'Costa Rica' },
  { name: 'Côte d´Ivoire' },
  { name: 'Dänemark' },
  { name: 'Deutschland' },
  { name: 'Dominica' },
  { name: 'Dominikanische Republik' },
  { name: 'Dschibuti' },
  { name: 'Ecuador' },
  { name: 'El Salvador' },
  { name: 'Eritrea' },
  { name: 'Estland' },
  { name: 'Europa' },
  { name: 'Falklandinseln' },
  { name: 'Färöer' },
  { name: 'Fidschi' },
  { name: 'Finnland' },
  { name: 'France, Metropolitan' },
  { name: 'Frankreich' },
  { name: 'Französische Süd- und Antarktisgebiete' },
  { name: 'Französisch-Guayana' },
  { name: 'Französisch-Polynesien' },
  { name: 'Gabun' },
  { name: 'Gambia' },
  { name: 'Gazastreifen' },
  { name: 'Georgien' },
  { name: 'Ghana' },
  { name: 'Gibraltar' },
  { name: 'Glorieuses' },
  { name: 'Grenada' },
  { name: 'Griechenland' },
  { name: 'Grönland' },
  { name: 'Großbritannien' },
  { name: 'Guadeloupe' },
  { name: 'Guam' },
  { name: 'Guatemala' },
  { name: 'Guernsey' },
  { name: 'Guinea' },
  { name: 'Guinea-Bissau' },
  { name: 'Guyana' },
  { name: 'Haiti' },
  { name: 'Heard und McDonaldinseln' },
  { name: 'Honduras' },
  { name: 'Hongkong' },
  { name: 'Indien' },
  { name: 'Indonesien' },
  { name: 'Insel Man' },
  { name: 'Irak' },
  { name: 'Iran' },
  { name: 'Irland' },
  { name: 'Island' },
  { name: 'Israel' },
  { name: 'Italien' },
  { name: 'Jamaika' },
  { name: 'Japan' },
  { name: 'Jemen' },
  { name: 'Jersey' },
  { name: 'Jordanien' },
  { name: 'Juan de Nova' },
  { name: 'Kaimaninseln' },
  { name: 'Kambodscha' },
  { name: 'Kamerun' },
  { name: 'Kanada' },
  { name: 'Kap Verde' },
  { name: 'Kasachstan' },
  { name: 'Katar' },
  { name: 'Kenia' },
  { name: 'Kirgisistan' },
  { name: 'Kiribati' },
  { name: 'Kleinere Amerikanische Überseeinseln' },
  { name: 'Kokosinseln (Keelinginseln)' },
  { name: 'Kolumbien' },
  { name: 'Komoren' },
  { name: 'Kongo' },
  { name: 'Kongo, Demokratische Republik' },
  { name: 'Korea, Demokratische Volksrepublik' },
  { name: 'Korea, Republik' },
  { name: 'Kroatien' },
  { name: 'Kuba' },
  { name: 'Kuwait' },
  { name: 'Laos' },
  { name: 'Lesotho' },
  { name: 'Lettland' },
  { name: 'Libanon' },
  { name: 'Liberia' },
  { name: 'Libyen' },
  { name: 'Liechtenstein' },
  { name: 'Litauen' },
  { name: 'Luxemburg' },
  { name: 'Macau' },
  { name: 'Madagaskar' },
  { name: 'Malawi' },
  { name: 'Malaysia' },
  { name: 'Malediven' },
  { name: 'Mali' },
  { name: 'Malta' },
  { name: 'Marokko' },
  { name: 'Marshallinseln' },
  { name: 'Martinique' },
  { name: 'Mauretanien' },
  { name: 'Mauritius' },
  { name: 'Mayotte' },
  { name: 'Mazedonien' },
  { name: 'Mexiko' },
  { name: 'Mikronesien' },
  { name: 'Moldau' },
  { name: 'Monaco' },
  { name: 'Mongolei' },
  { name: 'Montenegro' },
  { name: 'Montserrat' },
  { name: 'Mosambik' },
  { name: 'Myanmar' },
  { name: 'Namibia' },
  { name: 'Nauru' },
  { name: 'Nepal' },
  { name: 'Neukaledonien' },
  { name: 'Neuseeland' },
  { name: 'Nicaragua' },
  { name: 'Niederlande' },
  { name: 'Niederländische Antillen' },
  { name: 'Niger' },
  { name: 'Nigeria' },
  { name: 'Niue' },
  { name: 'Nördliche Marianen' },
  { name: 'Norfolkinsel' },
  { name: 'Norwegen' },
  { name: 'Oman' },
  { name: 'Österreich' },
  { name: 'Pakistan' },
  { name: 'Palau' },
  { name: 'Panama' },
  { name: 'Papua-Neuguinea' },
  { name: 'Paraguay' },
  { name: 'Peru' },
  { name: 'Philippinen' },
  { name: 'Pitcairninseln' },
  { name: 'Polen' },
  { name: 'Portugal' },
  { name: 'Puerto Rico' },
  { name: 'Réunion' },
  { name: 'Ruanda' },
  { name: 'Rumänien' },
  { name: 'Russische Föderation' },
  { name: 'Saint-Martin' },
  { name: 'Salomonen' },
  { name: 'Sambia' },
  { name: 'Samoa' },
  { name: 'San Marino' },
  { name: 'São Tomé und Príncipe' },
  { name: 'Saudi-Arabien' },
  { name: 'Schweden' },
  { name: 'Schweiz' },
  { name: 'Senegal' },
  { name: 'Serbien' },
  { name: 'Serbien und Montenegro' },
  { name: 'Seychellen' },
  { name: 'Sierra Leone' },
  { name: 'Simbabwe' },
  { name: 'Singapur' },
  { name: 'Slowakei' },
  { name: 'Slowenien' },
  { name: 'Somalia' },
  { name: 'Spanien' },
  { name: 'Spitzbergen' },
  { name: 'Sri Lanka' },
  { name: 'St. Barthélemy' },
  { name: 'St. Helena, Ascension und Tristan da Cunha' },
  { name: 'St. Kitts und Nevis' },
  { name: 'St. Lucia' },
  { name: 'St. Pierre und Miquelon' },
  { name: 'St. Vincent und die Grenadinen' },
  { name: 'Südafrika' },
  { name: 'Sudan' },
  { name: 'Südgeorgien und die Südlichen Sandwichinseln' },
  { name: 'Suriname' },
  { name: 'Swasiland' },
  { name: 'Syrien' },
  { name: 'Tadschikistan' },
  { name: 'Taiwan' },
  { name: 'Tansania' },
  { name: 'Thailand' },
  { name: 'Timor-Leste' },
  { name: 'Togo' },
  { name: 'Tokelau' },
  { name: 'Tonga' },
  { name: 'Trinidad und Tobago' },
  { name: 'Tromelin' },
  { name: 'Tschad' },
  { name: 'Tschechische Republik' },
  { name: 'Tunesien' },
  { name: 'Türkei' },
  { name: 'Turkmenistan' },
  { name: 'Turks- und Caicosinseln' },
  { name: 'Tuvalu' },
  { name: 'Uganda' },
  { name: 'Ukraine' },
  { name: 'Ungarn' },
  { name: 'Uruguay' },
  { name: 'Usbekistan' },
  { name: 'Vanuatu' },
  { name: 'Vatikanstadt' },
  { name: 'Venezuela' },
  { name: 'Vereinigte Arabische Emirate' },
  { name: 'Vereinigte Staaten' },
  { name: 'Vietnam' },
  { name: 'Wallis und Futuna' },
  { name: 'Weihnachtsinsel' },
  { name: 'Westjordanland' },
  { name: 'Westsahara' },
  { name: 'Zentralafrikanische Republik' },
  { name: 'Zypern' }
])